version: 2
updates:
  - package-ecosystem: npm
    commit-message:
      prefix: 'chore(npm-dep): '
    directory: '/'
    # Always increase package version to the latest version even if lockfile is the only thing required to change
    versioning-strategy: increase
    schedule:
      interval: daily
      time: '05:00'
      timezone: Europe/London
    open-pull-requests-limit: 99
