import fs from 'fs'
import path from 'path'
import { SUPPORTED_VARIANTS } from './build-utils/constants'
import { generateReactComponent } from './build-utils/generateReactComponent'
import { getSvgFiles } from './build-utils/getSvgFiles'
import { setupDirectories } from './build-utils/setupDirectories'

async function generateIcons(): Promise<void> {
  console.log('🎨 Building icon components...\n')

  if (!setupDirectories()) {
    return
  }

  const allProcessedIcons = SUPPORTED_VARIANTS.flatMap((variant) => {
    const svgFiles = getSvgFiles(variant)
    return svgFiles.map((file) => generateReactComponent(file, variant))
  })

  if (allProcessedIcons.length === 0) {
    console.log('No SVG files found to process')
    return
  }

  const iconExports = allProcessedIcons
    .map((icon) => icon.exportStatement)
    .sort()
    .join('\n')

  const generatedExportsContent = `// This file is auto-generated. Do not edit manually.
// Generated by npm run generate
${iconExports}
`

  fs.writeFileSync(
    path.join(process.cwd(), 'src', 'generated-exports.ts'),
    generatedExportsContent,
  )

  console.log('📄 Generated exports file: src/generated-exports.ts')
  console.log(`\n✅ Generated ${allProcessedIcons.length} React components!`)
  console.log(`📁 React components: src/icons/`)
}

generateIcons()
