import fs from 'fs'
import path from 'path'
import { ProcessedIcon } from './constants'

/**
 * Generate exports file for all icon components
 */
export function generateIndexFile(processedIcons: ProcessedIcon[]): void {
  const iconExports = processedIcons
    .map((icon) => icon.exportStatement)
    .sort()
    .join('\n')

  const generatedExportsContent = `// This file is auto-generated. Do not edit manually.
// Generated by npm run generate
${iconExports}
`

  // Write generated exports to a separate file
  fs.writeFileSync(
    path.join(process.cwd(), 'src', 'generated-exports.ts'),
    generatedExportsContent,
  )

  console.log('📄 Generated exports file: src/generated-exports.ts')
}
