name: Bump and Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  bump-and-publish:
    uses: marshmallow-insurance/campfire/.github/workflows/shared-semantic-release.yml@main
    secrets: inherit
